baseURL = "https://bbhtt.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
title = "Pixels"
theme = "hugo-notepadium"
enableRobotsTXT = false
hasCJKLanguage = false
rssLimit = 20
copyright = "Copyright © 2023 bbhtt and contributors"
relativeURLs = true

[author]
name = "bbhtt"
email = "bbhtt.zn0i8@slmail.me"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params]
style = "auto"
dateFormat = "Monday, January 2, 2006"
readingTime = true
logo = "/mine.png"
slogan = ""
license = ""
fullRss = true
ipv6ready = false

[params.comments]
enable = false

[params.math]
enable = false
use = "katex"

[params.syntax]
use = "none"
theme = "github"
darkTheme = "dracula"

[params.share]
enable = false
addThisId = ""
inlineToolId = ""

[params.nav]
showCategories = false
showTags = false

[[params.nav.custom]]
title = "Posts"
url = "/posts"

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Contact"
url = "/contact"
